# Generated by Django 4.2.2 on 2023-06-27 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('petwell_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pet',
            name='pet',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='pet',
            name='pet_breed',
            field=models.CharField(),
        ),
    ]
